import { Noto_Sans } from "next/font/google";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const noto_sans = Noto_Sans({
  subsets: ["cyrillic"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={noto_sans.className}>
        <h2 style={{ color: "#700b52" }}>Auth layout (app/(auth)/layout.tsx)</h2>
        {children}
      </body>
    </html>
  );
}
